#!/bin/sh
# Build IsGPTNerfed.app (menu bar app) with SwiftPM and assemble the bundle.
# Usage: ./macos/build.sh [--run | --install | --zip | --dmg | --release]     (needs Xcode 26+ / macOS 26 SDK)
#   --run      launch from the build folder
#   --install  copy to ~/Applications and launch
#   --zip      write dist/IsGPTNerfed-<version>.zip (+ .sha256), what the in-app updater downloads
#   --dmg      write dist/IsGPTNerfed-<version>.dmg (+ .sha256), for first-time downloads
#   --release  zip + dmg, notarized and stapled (needs SIGN_IDENTITY and NOTARY_PROFILE, see below)
#
# Signing: with SIGN_IDENTITY="Developer ID Application: Name (TEAMID)" in the environment the bundle is signed with
# that certificate, hardened runtime and a secure timestamp (what notarization requires); without it, ad-hoc, and a
# browser-downloaded copy is blocked on first launch (Privacy & Security → Open Anyway; install-app.sh avoids that).
# Notarization: NOTARY_PROFILE names a keychain profile made once with
#   xcrun notarytool store-credentials <profile> --apple-id <email> --team-id <TEAMID> --password <app-specific password>
set -eu
SIGN_IDENTITY="${SIGN_IDENTITY:-}"
NOTARY_PROFILE="${NOTARY_PROFILE:-}"

sign_bundle() {  # $1 = bundle or dmg
  if [ -n "$SIGN_IDENTITY" ]; then
    codesign --force --options runtime --timestamp --sign "$SIGN_IDENTITY" "$1"
  else
    codesign --force --sign - "$1" >/dev/null 2>&1 || true
  fi
}

notarize() {  # $1 = zip or dmg to submit; the stapler runs on $2 (app or dmg)
  [ -n "$NOTARY_PROFILE" ] || { echo "NOTARY_PROFILE is not set; see the header of this script" >&2; exit 1; }
  echo "notarizing $(basename "$1") …"
  if ! xcrun notarytool submit "$1" --keychain-profile "$NOTARY_PROFILE" --wait; then
    echo "notarization failed; the log:" >&2
    ID="$(xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" 2>/dev/null | grep -m1 -o 'id: [0-9a-f-]*' | cut -d' ' -f2 || true)"
    [ -n "$ID" ] && xcrun notarytool log "$ID" --keychain-profile "$NOTARY_PROFILE" >&2 || true
    exit 1
  fi
  xcrun stapler staple "$2" >/dev/null
}

make_zip() {  # $1 = out path
  rm -f "$1"; ditto -c -k --keepParent "$APP" "$1"
}

make_dmg() {  # $1 = out path
  rm -f "$1"
  STAGE="$(mktemp -d)"; cp -R "$APP" "$STAGE/"; ln -s /Applications "$STAGE/Applications"
  hdiutil create -volname "IsGPTNerfed $VERSION" -srcfolder "$STAGE" -ov -format UDZO "$1" >/dev/null
  rm -rf "$STAGE"
}
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
swift build -c release 2>&1 | grep -v '^\[' || true
BIN_DIR="$(swift build -c release --show-bin-path)"
BIN="$BIN_DIR/IsGPTNerfed"
[ -x "$BIN" ] || { echo "build failed: $BIN missing" >&2; exit 1; }
RESOURCE_BUNDLE="$BIN_DIR/IsGPTNerfed_IsGPTNerfed.bundle"
[ -d "$RESOURCE_BUNDLE" ] || { echo "build failed: $RESOURCE_BUNDLE missing" >&2; exit 1; }
APP="$HERE/build/IsGPTNerfed.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/IsGPTNerfed"
cp "$HERE/Info.plist" "$APP/Contents/Info.plist"
cp -R "$RESOURCE_BUNDLE" "$APP/Contents/Resources/"
cp "$HERE"/Resources/face-*.png "$APP/Contents/Resources/"   # panel header faces: ok / warn / alert
# icon: macos/icon.png (1024x1024, e.g. generated by Codex imagegen) wins; otherwise macos/icon.svg is
# rasterised with Quick Look, which every Mac has. Alternatives live in macos/icons/.
rm -f "$HERE/build/icon.svg.png" "$HERE/build/icon_1024.png"
if [ -f "$HERE/icon.png" ]; then
  sips -z 1024 1024 "$HERE/icon.png" --out "$HERE/build/icon_1024.png" >/dev/null
else
  qlmanage -t -s 1024 -o "$HERE/build" "$HERE/icon.svg" >/dev/null 2>&1
  mv "$HERE/build/icon.svg.png" "$HERE/build/icon_1024.png"
fi
ICONSET="$HERE/build/AppIcon.iconset"
rm -rf "$ICONSET"; mkdir -p "$ICONSET"
for s in 16 32 128 256 512; do
  sips -z $s $s "$HERE/build/icon_1024.png" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
  d=$((s*2)); sips -z $d $d "$HERE/build/icon_1024.png" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
# bundle the plugin as a local marketplace so the app can install itself into Codex (panel → Install)
MK="$APP/Contents/Resources/marketplace"
mkdir -p "$MK/.agents/plugins"
cp -R "$HERE/../plugin" "$MK/plugin"
cp "$HERE/../.agents/plugins/marketplace.json" "$MK/.agents/plugins/marketplace.json"
find "$MK" -name '__pycache__' -type d -prune -exec rm -rf {} +
chmod +x "$MK/plugin/skills/is-gpt-nerfed/scripts/nerfed"
sign_bundle "$APP"
echo "built $APP ($( [ -n "$SIGN_IDENTITY" ] && echo "signed: $SIGN_IDENTITY" || echo "ad-hoc signed" ))"
VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$HERE/Info.plist")"
DIST="$HERE/../dist"
case "${1:-}" in
  --run)
    pkill -x IsGPTNerfed 2>/dev/null || true
    open "$APP"
    echo "launched (menu bar)" ;;
  --install)
    DEST="$HOME/Applications/IsGPTNerfed.app"
    mkdir -p "$HOME/Applications"
    pkill -x IsGPTNerfed 2>/dev/null || true
    rm -rf "$DEST" && cp -R "$APP" "$DEST"
    for i in 1 2 3 4 5; do open "$DEST" 2>/dev/null && break; sleep 1; done   # LaunchServices can lag right after pkill
    echo "installed to $DEST and launched (menu bar); enable 'Launch at login' in the panel's settings" ;;
  --zip)
    mkdir -p "$DIST"; ZIP="$DIST/IsGPTNerfed-$VERSION.zip"
    make_zip "$ZIP"
    shasum -a 256 "$ZIP" | tee "$ZIP.sha256"
    echo "release archive: $ZIP" ;;
  --dmg)   # for people: a disk image with the app and an Applications shortcut (the updater uses the zip)
    mkdir -p "$DIST"; DMG="$DIST/IsGPTNerfed-$VERSION.dmg"
    make_dmg "$DMG"; sign_bundle "$DMG"
    shasum -a 256 "$DMG" | tee "$DMG.sha256"
    echo "disk image: $DMG" ;;
  --release)   # signed, notarized, stapled zip + dmg; attach all four files (and the two .sha256) to the GitHub release
    [ -n "$SIGN_IDENTITY" ] || { echo "SIGN_IDENTITY is not set (Developer ID Application certificate); see the header" >&2; exit 1; }
    mkdir -p "$DIST"; ZIP="$DIST/IsGPTNerfed-$VERSION.zip"; DMG="$DIST/IsGPTNerfed-$VERSION.dmg"
    make_zip "$ZIP"; notarize "$ZIP" "$APP"        # the ticket is stapled to the app …
    make_zip "$ZIP"                                # … so the zip is rebuilt from the stapled app
    shasum -a 256 "$ZIP" | tee "$ZIP.sha256"
    make_dmg "$DMG"; sign_bundle "$DMG"; notarize "$DMG" "$DMG"
    shasum -a 256 "$DMG" | tee "$DMG.sha256"
    spctl -a -vv "$APP" 2>&1 | tail -2
    echo "release files: $ZIP $DMG (+ .sha256 each)" ;;
esac
